#!/usr/bin/env ruby

ENGINE_PATH = File.expand_path('../../', __FILE__)
APP_PATH = File.expand_path('../../../config/application', __FILE__)
require File.expand_path('../../../config/boot', __FILE__)
require 'rails/commands'

